{% set name = "PyPDFForm" %}
{% set version = "1.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v{{ version }}.tar.gz
  sha256: 36a9406fc3fcda01660cc42decd35d6b35cf14cc8e60fdd49523b4d3a2be14fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cryptography
    - pillow
    - pypdf
    - reportlab

test:
  imports:
    - PyPDFForm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chinapandaman/PyPDFForm
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
