{% set name = "PyPDFForm" %}
{% set version = "1.4.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v{{ version }}.tar.gz
  sha256: 115a46d04b1722a15f82f0e91cee5d92ba3a900bb8288bf2dde26456235dd682

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cryptography
    - pillow
    - pypdf
    - reportlab

test:
  imports:
    - PyPDFForm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chinapandaman/PyPDFForm
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
