{% set name = "PyPDFForm" %}
{% set version = "1.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v{{ version }}.tar.gz
  sha256: 0a9669dde11a19b83d34840fa5df46c01395169445dd267c6da798d58a04e56c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cryptography
    - pillow
    - pypdf
    - reportlab

test:
  imports:
    - PyPDFForm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chinapandaman/PyPDFForm
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
