{% set name = "PyPDFForm" %}
{% set version = "1.4.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v{{ version }}.tar.gz
  sha256: 56243842d8e61550446049740315006cf9a96b5224026d977026056781e61e0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cryptography
    - pillow
    - pypdf
    - reportlab

test:
  imports:
    - PyPDFForm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chinapandaman/PyPDFForm
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
