{% set name = "PyPDFForm" %}
{% set version = "1.4.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v{{ version }}.tar.gz
  sha256: a669f38757f9c70e71341002ccb22561debc3a09de98fcd412911caad2d79610

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cryptography
    - pillow
    - pypdf
    - reportlab

test:
  imports:
    - PyPDFForm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chinapandaman/PyPDFForm
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
