schema_version: 1

context:
  name: PyPDFForm
  version: "2.2.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v${{ version }}.tar.gz
  sha256: 6de10318d8135e1fe8a58ded67c9b63ff1ef295e93cf78627516c935d44fea29

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cryptography
    - pillow
    - pypdf
    - reportlab

tests:
  - python:
      imports:
        - PyPDFForm
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chinapandaman/PyPDFForm

extra:
  recipe-maintainers:
    - thewchan
