schema_version: 1

context:
  name: PyPDFForm
  version: "3.5.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v${{ version }}.tar.gz
  sha256: 4a076446e59af269d1d089f71566126700a67b2c8c01dc0c10ee6c9ba8389b56

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cryptography
    - fonttools
    - pillow
    - pypdf
    - reportlab

tests:
  - python:
      imports:
        - PyPDFForm
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chinapandaman/PyPDFForm

extra:
  recipe-maintainers:
    - thewchan
