schema_version: 1

context:
  name: PyPDFForm
  version: "3.7.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v${{ version }}.tar.gz
  sha256: 7487a00e3091c63c085f752f67b9d9519a94752183c990054ad9b4692b9d20fa

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cryptography
    - fonttools
    - pikepdf
    - pillow
    - pypdf
    - reportlab

tests:
  - python:
      imports:
        - PyPDFForm
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chinapandaman/PyPDFForm

extra:
  recipe-maintainers:
    - thewchan
