schema_version: 1

context:
  name: PyPDFForm
  version: "3.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v${{ version }}.tar.gz
  sha256: 1e4cf8bbb4cf3d1fe5f18e5e9c82ddf42f5a1d76c1d3a804cb6d0ab6bd557d50

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cryptography
    - pillow
    - pypdf
    - reportlab

tests:
  - python:
      imports:
        - PyPDFForm
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chinapandaman/PyPDFForm

extra:
  recipe-maintainers:
    - thewchan
