schema_version: 1

context:
  name: PyPDFForm
  version: "4.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v${{ version }}.tar.gz
  sha256: f8eeb6c860560c578773b77d880c70859b6b7bd6212f5b9a3837d49dc3e7d3cc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cryptography
    - fonttools
    - pikepdf
    - pillow
    - pypdf
    - reportlab

tests:
  - python:
      imports:
        - PyPDFForm
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chinapandaman/PyPDFForm

extra:
  recipe-maintainers:
    - thewchan
